version: '3.1'
services:
  ghost:
    image: ghost:${GHOST_VERSION}
    restart: always
    depends_on:
      ghost-db:
        condition: service_healthy
    networks:
      - ghost-network
    ports:
      - "${APP_PORT}:2368"
    volumes:
      - "./ghost-content:/var/lib/ghost/content"
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      # this url value is just an example, and is likely wrong for your environment!
      url: ${APP_URL}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: ${APP_ENV}

  ghost-db:
    image: mysql:8.0
    restart: always
    networks:
      - ghost-network
    volumes:
      - "./ghost-db:/var/lib/mysql"
    healthcheck:
      test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 20s
      retries: 30
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

networks:
  ghost-network:
      driver: bridge