version: '3.1'
services:
  ghost:
    image: ghost:${GHOST_VERSION}
    container_name: ${CONTAINER_SLUG}_app
    restart: unless-stopped
    depends_on:
      ghost-db:
        condition: service_healthy
    networks:
      - ghost-network
    ports:
      - "${CONTAINER_PORT}:2368"
    volumes:
      - "./data/ghost-content:/var/lib/ghost/content"
      - "./data/ghost-config/config.json:/var/lib/ghost/config.production.json:z"
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_NAME}
      NODE_ENV: production

  ghost-db:
    image: mysql:8.0
    container_name: ${CONTAINER_SLUG}_db
    restart: unless-stopped
    networks:
      - ghost-network
    volumes:
      - "./data/mysql-data:/var/lib/mysql"
    healthcheck:
      test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 1m
      retries: 30
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

networks:
  ghost-network:
      driver: bridge